version: '3.4'

services:
  tasklistapi:
    image: tasklistapi
    build:
      context: .
      dockerfile: TaskListApi/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - MONGODB_URI=mongodb://root:12345@mongo:27017/TaskListApi?authSource=admin
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "12345"
